version: '3.8'
name: 'brizzi_invoice'

services:
  postgres:
    image: postgres:16-alpine
    container_name: brizzi_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brizzi_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: